### ISSUE TITLE
Configuration assistance

### ISSUE THREAD

**Issue by yarons** [haxpax/gosms#7]
I want to run the app on Linux and I can't really figure out the COMPORT value.

How do I find my device? Should I write the device as /dev/tty... or COMn?

Thanks!

**Comment by Omie** [comment]
hi @yarons 

in Linux its usually `/dev/ttyusb0` depending on number of devices connected.
I am not sure if `lsusb -v` provides this information. See if it shows anything, otherwise you can do `ls -l /dev/tty*` to check if any such device exists. or check output of `dmesg` after plugging in device or do tail on syslog and connect the device `tail -f /var/log/syslog` then check the output.

note that location of syslog could be different depending on your distribution. This one is for Ubuntu.

feel free to get back if you need anything more.

**Comment by yarons** [comment]
Yes but can I enter this path into the config?
Is there any documentation about that in the config?

Thanks!

**Comment by Omie** [comment]
yes you can use that. not referenced in docs.

**Comment by yarons** [comment]
Do you mind if I add that to the docs?

**Comment by Omie** [comment]
heh! not at all :)
